<table class="table">
	<thead>
		<th>
			Customer Name
		</th>
		<th>
			phone
		</th>
		<th>
			Quantity
		</th>
		<th>
			City 
		</th>
		<th>
			Date
		</th>
		<th>
			Time
		</th>
		<th>	
			Train
		</th>
		<th>
			Price
		</th>
		<th>
			Total
		</th>
		<th>
			<a href="choose" class="btn btn-primary">New booking</a>
		</th>
	</thead>
	<?php
		$totalQty = 0;
		$totalPrice  = 0;
		$totalNet = 0;
		foreach ($this->bookingList as $booking) {
			$totalQty += $booking['quantity'];
			$totalPrice += $booking['price'];
			$totalNet += $booking['price']*$booking['quantity'];
			echo "<tr>";		
			echo "<td>".$booking['name']."</td>";		
			echo "<td>".$booking['phone']."</td>";			
			echo "<td>".$booking['quantity']."</td>";
			echo "<td>".$booking['destination_city']."</td>";
			echo "<td>".$booking['date']."</td>";
			echo "<td>".$booking['time']."</td>";
			echo "<td>".$booking['train_number']."</td>";						
			echo "<td>".$booking['price']."</td>";
			echo "<td>".$booking['price']*$booking['quantity']."</td>";
			echo "</tr>";		
		}
		echo "<tr>";
		echo "<td></td>";
		echo "<td></td>";
		echo "<td>".$totalQty."</td>";
		echo "<td></td>";
		echo "<td></td>";
		echo "<td></td>";
		echo "<td></td>";
		echo "<td>".$totalPrice."</td>";
		echo "<td>".$totalNet."</td>";
		echo "</tr>";

	?>
</table>

