<table class="table">
	<thead>
		<th>
			Customer Name
		</th>
		<th>
			phone
		</th>
		<th>
			Quantity
		</th>
		<th>
			City 
		</th>
		<th>
			Date
		</th>
		<th>
			Time
		</th>
		<th>	
			Train
		</th>
		<th>
			Price
		</th>
		<th>
			Total
		</th>
		<th>
			<a href="choose" class="btn btn-primary">New booking</a>
		</th>
	</thead>
	<?php
		foreach ($this->bookingList as $booking) {
			echo "<tr>";		
			echo "<td>".$booking['name']."</td>";		
			echo "<td>".$booking['phone']."</td>";			
			echo "<td>".$booking['quantity']."</td>";
			echo "<td>".$booking['destination_city']."</td>";
			echo "<td>".$booking['date']."</td>";
			echo "<td>".$booking['time']."</td>";
			echo "<td>".$booking['train_number']."</td>";						
			echo "<td>".$booking['price']."</td>";
			echo "<td>".$booking['price']*$booking['quantity']."</td>";
			if($booking['status']=="unprocess"){
				echo "<td> <a href='generate?id=".$booking['booking_id']."' class='btn btn-primary'>"."confirm"."</a></td>";
				echo "<td> <a href='reject?id=".$booking['booking_id']."' class='btn btn-danger'>"."reject"."</a></td>";
			}
			echo "</tr>";		
		}
	?>
</table>