<?php
?>
<table class="table">
	<form method="post">
		<tr>
			<td>
				<label name="class">Class</label>	
			</td>
			<td>
				<input type="text" name="class" class="form-control" value="<?php echo $this->train['class']; ?>" />
				<input name="trainId" type="hidden" value="<?php echo $this->train['train_id']; ?>" />
			</td>
		</tr>
		<tr>
			<td>
				<label name="numOfTrolley">Number Of Trolley</label>	
			</td>
			<td>
				<input type="number" name="numOfTrolley" class="form-control" value="<?php echo $this->train['num_of_trolley']; ?>" />
			</td>
		</tr>
		<tr>
			<td>
				<label name="trainNumber">Train Number</label>	
			</td>
			<td>
				<input type="text" name="trainNumber" class="form-control" value="<?php echo $this->train['train_number']; ?>" />
			</td>
		</tr>
		<tr>
			<td>
			</td>
			<td>
				<input type="submit" class="btn btn-primary" value="update"/>
			</td>
		</tr>
	</form>
</table>
