<?php
	
?>
<table class="table">
	<form method="post">
		<tr>
			<td>
				<label name="class">Class</label>	
			</td>
			<td>
				<input type="text" name="class" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				<label name="numOfTrolley">Number Of Trolley</label>	
			</td>
			<td>
				<input type="number" name="numOfTrolley" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				<label name="trainNumber">Train Number</label>	
			</td>
			<td>
				<input type="text" name="trainNumber" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
			</td>
			<td>
				<input type="submit" class="btn btn-primary" value="save" />
			</td>
		</tr>
	</form>
</table>