<!DOCTYPE html>
<html>
<head>
	<title>MM Railway</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href='<?php echo $this->baseUrl()."/css/reset.css"; ?>' type="text/css" media="all" />
	
 <link rel="stylesheet" href='<?php echo $this->baseUrl()."/css/layout.css"; ?>' type="text/css" media="all">
<link rel="stylesheet" href='<?php echo $this->baseUrl()."/css/style.css"; ?>' type="text/css" media="all">

<link rel="stylesheet" href='<?php echo $this->baseUrl()."/css/bootstrap.min.css"; ?>' type="text/css" media="all">



	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/jquery-1.5.2.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/cufon-yui.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/cufon-replace.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/Cabin_400.font.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/tabs.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/jquery.jqtransform.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/jquery.nivo.slider.pack.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/atooltip.jquery.js"; ?>' ></script>
	<script type="text/javascript" src='<?php echo $this->baseUrl()."js/script.js";?>' ></script>	
	
</head>
<body id="page1">
<div class="main">
  <!--header -->
  <header>
    <div class="wrapper">
      <h1><a href="index.html" id="logo">AirLines</a></h1>
      <span id="slogan">Fast, Frequent &amp; Safe Flights</span>
      <nav id="top_nav" >
        <ul>
          <li><a href="index.html" class="nav1">Home</a></li>
          <li><a href="#" class="nav2">Sitemap</a></li>
          <li><a href="contacts.html" class="nav3">Contact</a></li>
        </ul>
      </nav>
    </div>
    <nav class="nav" style="display: block; height: 20%;">
      <ul id="menu">
        <li id="menu_active"><a href=<?php echo $this->baseUrl()."/train/index" ;?> ><span><span>Train</span></span></a></li>
        <li id="menu_active"><a href=<?php echo $this->baseUrl()."/schedule/index" ;?>><span><span>Schedule</span></span></a></li>
        <li id="menu_active"><a href=<?php echo $this->baseUrl()."/customer/index" ;?>><span><span>Customer</span></span></a></li>
        <li id="menu_active"><a href=<?php echo $this->baseUrl()."/booking/index" ;?>><span><span>Booking</span></span></a></li>
        <li id="menu_active"><a href="safety.html"><span><span>Safety</span></span></a></li>

      </ul>
    </nav>
  </header>
  <!-- / header -->
  <!--content -->

  <section>
      <?php echo $this->layout()->content;?>
  </section>

<div style="background:gray">
    My footer
</div>
</body>
</html>